services:
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./dist/apps/fintechain-website:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always